In [13]:
import pandas as pd
from pathlib import Path
import json

In [28]:
def get_latest_file(folder, glob_str):
    files = list(folder.glob(glob_str))
    return sorted(files)[-1]

### Ghostfolio Activities

In [12]:
ghostfolio_folder = Path("/Users/veselda7/Library/CloudStorage/GoogleDrive-veselda7@gmail.com/My Drive/S Kačenkou/Investovani/ghostfolio")

latest_ghostfolio_file = get_latest_file(ghostfolio_folder, "*.json")
print(latest_ghostfolio_file.name)

ghostfolio-export-202504032149.json

In [14]:
with latest_ghostfolio_file.open("r", encoding="utf-8") as f:
    data = json.load(f)

In [22]:
gf_activities = pd.DataFrame(data["activities"])
gf_activities.head()

,accountId,comment,fee,quantity,type,unitPrice,currency,dataSource,date,symbol,tags
0,988e932b-52c7-48df-bd8d-37987582e416,None,3.21,0.20610,BUY,4456.45,USD,YAHOO,2017-09-10T22:00:00.000Z,BTC-USD,[]
1,988e932b-52c7-48df-bd8d-37987582e416,None,0.06,100.00000,BUY,0.25,USD,YAHOO,2017-10-11T22:00:00.000Z,XRP-USD,[]
2,988e932b-52c7-48df-bd8d-37987582e416,None,2.40,0.12040,BUY,5694.24,USD,YAHOO,2017-10-23T22:00:00.000Z,BTC-USD,[]
3,988e932b-52c7-48df-bd8d-37987582e416,None,0.80,0.04149,BUY,5529.84,USD,YAHOO,2017-10-24T22:00:00.000Z,BTC-USD,[]
4,988e932b-52c7-48df-bd8d-37987582e416,None,0.84,0.04149,SELL,5757.27,USD,YAHOO,2017-10-25T22:00:00.000Z,BTC-USD,[]

### Xtb

In [29]:
xtb_folder = Path("/Users/veselda7/Library/CloudStorage/GoogleDrive-veselda7@gmail.com/My Drive/S Kačenkou/Investovani/xtb")
xtb_file = get_latest_file(xtb_folder, "*.xlsx")
print(xtb_file.name)

account_51703073_en_xlsx_2024-12-31_2025-04-03.xlsx

In [35]:
 with pd.ExcelFile(xtb_file) as excel_file:
    open_sheet = next(name for name in excel_file.sheet_names if "OPEN POSITION" in name)

In [39]:
pd.read_excel(xtb_file, sheet_name=open_sheet, skiprows=10, usecols="B:Q")

,Position,Symbol,Type,Volume,Open time,Open price,Market price,Purchase value,SL,TP,Margin,Commission,Swap,Rollover,Gross P/L,Comment
0,1645385488,QDVE.DE,BUY,0.4249,2025-02-06 09:44:06.372,32.260,27.595,346.42,NaN,NaN,0.0,0.0,0.0,0.0,-56.14,NaN
1,1682230158,QDVE.DE,BUY,0.4408,2025-03-03 09:05:51.949,31.195,27.595,346.49,NaN,NaN,0.0,0.0,0.0,0.0,-45.35,NaN
2,1693255188,QDVE.DE,BUY,0.4795,2025-03-07 09:36:08.720,28.700,27.595,346.46,NaN,NaN,0.0,0.0,0.0,0.0,-18.88,NaN
3,1653751854,QDVE.DE,BUY,0.4220,2025-02-12 10:04:05.912,32.540,27.595,346.41,NaN,NaN,0.0,0.0,0.0,0.0,-58.11,NaN
4,1643459454,QDVE.DE,BUY,0.4364,2025-02-05 10:08:10.371,31.395,27.595,346.49,NaN,NaN,0.0,0.0,0.0,0.0,-48.35,NaN
5,1643300948,QDVE.DE,BUY,0.4326,2025-02-05 09:04:02.861,31.675,27.595,346.35,NaN,NaN,0.0,0.0,0.0,0.0,-50.81,NaN
6,1685148208,QDVE.DE,BUY,0.4608,2025-03-04 10:00:12.320,29.860,27.595,346.46,NaN,NaN,0.0,0.0,0.0,0.0,-31.66,NaN
7,1690759774,QDVE.DE,BUY,0.4736,2025-03-06 09:42:16.737,29.085,27.595,346.45,NaN,NaN,0.0,0.0,0.0,0.0,-22.90,NaN
8,1651851749,QDVE.DE,BUY,0.4226,2025-02-11 10:04:12.915,32.495,27.595,346.48,NaN,NaN,0.0,0.0,0.0,0.0,-57.77,NaN
9,1650026204,QDVE.DE,BUY,0.4246,2025-02-10 11:24:09.913,32.350,27.595,346.51,NaN,NaN,0.0,0.0,0.0,0.0,-56.44,NaN
10,1736091680,QDVE.DE,BUY,0.5022,2025-04-02 10:03:52.853,27.520,27.595,346.52,NaN,NaN,0.0,0.0,0.0,0.0,-3.43,NaN
11,1647215166,QDVE.DE,BUY,0.4250,2025-02-07 09:36:10.375,32.320,27.595,346.44,NaN,NaN,0.0,0.0,0.0,0.0,-56.09,NaN
12,1655925257,QDVE.DE,BUY,0.4258,2025-02-13 09:52:09.912,32.300,27.595,346.47,NaN,NaN,0.0,0.0,0.0,0.0,-55.58,NaN
13,1696190710,QDVE.DE,BUY,0.9744,2025-03-10 09:04:09.453,28.765,27.595,703.49,NaN,NaN,0.0,0.0,0.0,0.0,-37.81,NaN
14,1688195124,QDVE.DE,BUY,0.4670,2025-03-05 10:06:08.721,29.475,27.595,346.56,NaN,NaN,0.0,0.0,0.0,0.0,-27.52,NaN
15,1660226875,QDVE.DE,BUY,0.4223,2025-02-17 09:04:27.419,32.605,27.595,346.99,NaN,NaN,0.0,0.0,0.0,0.0,-58.49,NaN
16,1657954825,QDVE.DE,BUY,0.4223,2025-02-14 09:42:11.910,32.615,27.595,346.48,NaN,NaN,0.0,0.0,0.0,0.0,-57.98,NaN
17,1649716328,QDVE.DE,BUY,0.8520,2025-02-10 09:04:03.732,32.350,27.595,695.01,NaN,NaN,0.0,0.0,0.0,0.0,-112.95,NaN
18,1739169323,QDVE.DE,BUY,0.5251,2025-04-03 10:00:08.845,26.255,NaN,346.45,NaN,NaN,0.0,0.0,0.0,0.0,0.00,NaN
19,Total,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,-856.26,NaN